<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AdminMenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        $tableName = 'menus';
        
        \DB::table($tableName)->delete();
        
        \DB::table($tableName)->insert(array (
            0 => 
            array (
                'id' => 2,
                'father_menu_id' => 1,
                'menu_title' => 'Home',
                'route' => 'HOME_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '8084d2014eff3a7b21d7d031f36279eb',
                'db_table_id' => 1,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            1 => 
            array (
                'id' => 14,
                'father_menu_id' => 400,
                'menu_title' => 'ADICIONAR_PERFIL',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'dc211d992b7e397b158d3103f2b9cf5a',
                'db_table_id' => NULL,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            2 => 
            array (
                'id' => 15,
                'father_menu_id' => 400,
                'menu_title' => 'LISTAR_PERFIS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'de2e2b248a0ba65ed3f11c2bdf6c9a53',
                'db_table_id' => NULL,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            3 => 
            array (
                'id' => 33,
                'father_menu_id' => 31,
                'menu_title' => 'LISTAR_TABELAS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'table',
                'menu_url_hash' => '71deca3bdc0f642e4ce1fa892929da7a',
                'db_table_id' => 6,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            4 => 
            array (
                'id' => 37,
                'father_menu_id' => 31,
                'menu_title' => 'LISTAR_CAMPOS_TABELA',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'b832bac46147eab1b8dde6852058f864',
                'db_table_id' => 11,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            5 => 
            array (
                'id' => 100,
                'father_menu_id' => NULL,
                'menu_title' => 'ADMINISTRACAO',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'cogs',
                'menu_url_hash' => '9212b503339c08ed8a0360f0dd4912cd',
                'db_table_id' => NULL,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            6 => 
            array (
                'id' => 16,
                'father_menu_id' => 400,
                'menu_title' => 'VIEW_ROLE',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '972dc026d07b74a3918783b74a929cd6',
                'db_table_id' => NULL,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            7 => 
            array (
                'id' => 4,
                'father_menu_id' => 100,
                'menu_title' => 'USUARIOS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'users',
                'menu_url_hash' => '987f94b6b2866343e9c54edd250fc259',
                'db_table_id' => NULL,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            8 => 
            array (
                'id' => 7,
                'father_menu_id' => 4,
                'menu_title' => 'ADICIONAR_USUARIO',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'c038d4c071567f8673f2e51a4069f25c',
                'db_table_id' => NULL,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            9 => 
            array (
                'id' => 41,
                'father_menu_id' => 4,
                'menu_title' => 'EDITAR_USUARIO',
                'route' => 'CRUD_VIEW',
                'opt_show_menu' => NULL,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '7475ae2fd02e1086cea4973630445a45',
                'db_table_id' => 2,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            10 => 
            array (
                'id' => 43,
                'father_menu_id' => 100,
                'menu_title' => 'VISUALIZACAO',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'screwdriver',
                'menu_url_hash' => 'd01fef50b51726275f3feca3c70e4dea',
                'db_table_id' => 3,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            11 => 
            array (
                'id' => 45,
                'father_menu_id' => 44,
                'menu_title' => 'EDIT_DICTIONARY_WORD',
                'route' => 'CRUD_VIEW',
                'opt_show_menu' => NULL,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'ea134e4b4256fc2f0f88109021c9b07f',
                'db_table_id' => 32,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            12 => 
            array (
                'id' => 47,
                'father_menu_id' => 44,
                'menu_title' => 'ADD_DICTIONARY_TRANSLATION',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '9ae9cb587594021cd28e7cce953d97f6',
                'db_table_id' => 33,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            13 => 
            array (
                'id' => 49,
                'father_menu_id' => 31,
                'menu_title' => 'RELACIONAR_CAMPOS_TABELA',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '79784338ee2e9c6c1185a24465f743db',
                'db_table_id' => 13,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            14 => 
            array (
                'id' => 51,
                'father_menu_id' => 31,
                'menu_title' => 'LIST_FIELD_JOINTS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '072d411b7681fc2091418482db2735ad',
                'db_table_id' => 13,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            15 => 
            array (
                'id' => 5,
                'father_menu_id' => 100,
                'menu_title' => 'MENUS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'bars',
                'menu_url_hash' => '9f6e4f167614a21b8de52e38531a1662',
                'db_table_id' => NULL,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            16 => 
            array (
                'id' => 200,
                'father_menu_id' => NULL,
                'menu_title' => 'CONTEUDO',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'icon-prd',
                'menu_url_hash' => '8f11553e223f69cd6938f0e0a5ca3106',
                'db_table_id' => NULL,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            17 => 
            array (
                'id' => 11,
                'father_menu_id' => 200,
                'menu_title' => 'MODELOS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '079d8e7f8990b3a5d281798269d0b79d',
                'db_table_id' => NULL,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            18 => 
            array (
                'id' => 10,
                'father_menu_id' => 200,
                'menu_title' => 'PRODUTOS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'icon-prd',
                'menu_url_hash' => '90b370c685f47bc1f300559a24d4b03c',
                'db_table_id' => NULL,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            19 => 
            array (
                'id' => 300,
                'father_menu_id' => NULL,
                'menu_title' => 'MTG',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 0,
                'class_fa_icon' => 'icon-mtg',
                'menu_url_hash' => 'a79441ea707855e0896395fd9baaf0db',
                'db_table_id' => NULL,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            20 => 
            array (
                'id' => 28,
                'father_menu_id' => 300,
                'menu_title' => 'CARTAS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '4c1ce9bd11d5e36158c4d8fa3dc8e9f1',
                'db_table_id' => NULL,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            21 => 
            array (
                'id' => 32,
                'father_menu_id' => 5,
                'menu_title' => 'ADICIONAR_MENU',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'f7297421861662291eddeb6179378a0d',
                'db_table_id' => 3,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            22 => 
            array (
                'id' => 36,
                'father_menu_id' => 31,
                'menu_title' => 'ADICIONAR_TABELA',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'table',
                'menu_url_hash' => '51d1147595b4dc439c0cb4683ccd7322',
                'db_table_id' => 6,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            23 => 
            array (
                'id' => 8,
                'father_menu_id' => 200,
                'menu_title' => 'ARTIGOS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '784949445fe212956e95a460fb824d7c',
                'db_table_id' => NULL,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            24 => 
            array (
                'id' => 23,
                'father_menu_id' => 100,
                'menu_title' => 'IMPORTADOR',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'arrow-down',
                'menu_url_hash' => '3625f554c8528bf453c5a695d6942f84',
                'db_table_id' => NULL,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            25 => 
            array (
                'id' => 31,
                'father_menu_id' => 100,
                'menu_title' => 'DATABASE',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'database',
                'menu_url_hash' => '965ac7557dc20d67047043ecbed46ae4',
                'db_table_id' => NULL,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            26 => 
            array (
                'id' => 6,
                'father_menu_id' => 4,
                'menu_title' => 'LISTAR_USUARIOS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'bf4fc0f7f9966228b29a2b6e1813f0b7',
                'db_table_id' => 2,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            27 => 
            array (
                'id' => 40,
                'father_menu_id' => 31,
                'menu_title' => 'EDITAR_TABELA',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '997423f712aa8fd8e10f38a9afbb3c48',
                'db_table_id' => 6,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            28 => 
            array (
                'id' => 44,
                'father_menu_id' => 100,
                'menu_title' => 'DICTIONARY',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'book',
                'menu_url_hash' => 'dca0aae7fb14c689e8757742c76045a6',
                'db_table_id' => 2,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            29 => 
            array (
                'id' => 46,
                'father_menu_id' => 44,
                'menu_title' => 'LIST_DICTIONARY_WORDS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '08bc460efd6d7b6b5501bf115c8c7ebe',
                'db_table_id' => 32,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            30 => 
            array (
                'id' => 50,
                'father_menu_id' => 5,
                'menu_title' => 'EDITAR_MENU',
                'route' => 'CRUD_VIEW',
                'opt_show_menu' => NULL,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'c6177de3c5d54b9edc1e2e04fcfe43d5',
                'db_table_id' => 3,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            31 => 
            array (
                'id' => 9,
                'father_menu_id' => 8,
                'menu_title' => 'LISTAR_ARTIGOS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'icon-prd',
                'menu_url_hash' => '1cf31abde0e4254b12fc09c499933f64',
                'db_table_id' => 37,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            32 => 
            array (
                'id' => 52,
                'father_menu_id' => 31,
                'menu_title' => 'EDITAR_CAMPO_EXTRANGEIRO',
                'route' => 'CRUD_VIEW',
                'opt_show_menu' => NULL,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '8f05329a3c2a90e9f2b6fa3f5e822273',
                'db_table_id' => 13,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            33 => 
            array (
                'id' => 38,
                'father_menu_id' => 31,
                'menu_title' => 'ADICIONAR_CAMPOS_TABELA',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '48d507a1af1f3f26b0d96ab176107a96',
                'db_table_id' => 11,
                'return_to_menu_id' => 37,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            34 => 
            array (
                'id' => 48,
                'father_menu_id' => 31,
                'menu_title' => 'EDITAR_CAMPO_TABELA',
                'route' => 'CRUD_VIEW',
                'opt_show_menu' => NULL,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '0d305d3368202beb084b757d11394e31',
                'db_table_id' => 11,
                'return_to_menu_id' => 37,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            35 => 
            array (
                'id' => 1,
                'father_menu_id' => NULL,
                'menu_title' => 'HOME',
                'route' => 'HOME_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'icon-home',
                'menu_url_hash' => 'ebc11b9610e2dbc927c230572624a014',
                'db_table_id' => 1,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            36 => 
            array (
                'id' => 22,
                'father_menu_id' => 8,
                'menu_title' => 'VIEW_ARTIGO',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'cf4f1627d6deceec9e44960a34e8c3a1',
                'db_table_id' => NULL,
                'return_to_menu_id' => 22,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            37 => 
            array (
                'id' => 59,
                'father_menu_id' => 31,
                'menu_title' => 'LIST_DATABASES',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'database',
                'menu_url_hash' => '2fdce19f21d3424597bbfc92a269bce3',
                'db_table_id' => 9,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            38 => 
            array (
                'id' => 25,
                'father_menu_id' => 23,
                'menu_title' => 'INSERIR_IMPORTADOR',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'd168545cfcb74d58de1b443e604f6954',
                'db_table_id' => 15,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            39 => 
            array (
                'id' => 12,
                'father_menu_id' => 10,
                'menu_title' => 'LISTAR_PRODUTOS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '087191174a91f7d5a73acb8a1d760a34',
                'db_table_id' => 39,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            40 => 
            array (
                'id' => 26,
                'father_menu_id' => 5,
                'menu_title' => 'LISTAR_MENUS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '24c007b328f19943bc53bf4715f9fe6b',
                'db_table_id' => 3,
                'return_to_menu_id' => 48,
                'custom_crud_view' => NULL,
                'custom_controller' => 'Menus',
                'custom_first_method_get' => 'index',
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            41 => 
            array (
                'id' => 53,
                'father_menu_id' => 100,
                'menu_title' => 'TESTES',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'ac458410f4ada3be8f576477eef41ce3',
                'db_table_id' => 41,
                'return_to_menu_id' => 100,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            42 => 
            array (
                'id' => 54,
                'father_menu_id' => 53,
                'menu_title' => 'LISTAR_TESTES',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '2c7ac929a02f2857b8d15bef01193dd0',
                'db_table_id' => 41,
                'return_to_menu_id' => 53,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            43 => 
            array (
                'id' => 24,
                'father_menu_id' => 23,
                'menu_title' => 'IMPORTADOR',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'cee5d729e0f43173fc56d65ec4afb222',
                'db_table_id' => 15,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            44 => 
            array (
                'id' => 39,
                'father_menu_id' => 31,
                'menu_title' => 'RELACIONAR_TABELAS',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'database',
                'menu_url_hash' => '5d6be589684984505435e6b53a6874f7',
                'db_table_id' => 23,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            45 => 
            array (
                'id' => 400,
                'father_menu_id' => 100,
                'menu_title' => 'PERFIS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'address-card',
                'menu_url_hash' => 'fdbcc17be502e5192b8dfe1edfdfba38',
                'db_table_id' => 2,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            46 => 
            array (
                'id' => 58,
                'father_menu_id' => 5,
                'menu_title' => 'MENU_LIST_ACTIONS_ADD',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '673acf5da3f4a2a96293ff0fb3781eea',
                'db_table_id' => 31,
                'return_to_menu_id' => 26,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            47 => 
            array (
                'id' => 61,
                'father_menu_id' => 31,
                'menu_title' => 'ADMIN_DB_ADD_DATABASE',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '99e8f8df060c56aec39585267bd99f5e',
                'db_table_id' => 9,
                'return_to_menu_id' => 59,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            48 => 
            array (
                'id' => 13,
                'father_menu_id' => 11,
                'menu_title' => 'LISTAR_MODELOS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '41fa02c4e9a3ecbcde545b8bd7e3c9ec',
                'db_table_id' => 38,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            49 => 
            array (
                'id' => 62,
                'father_menu_id' => 5,
                'menu_title' => 'ADMIN_MENUS_ADD_RELATED_MENU',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '132878f048adc0cb452f43bca3abcd60',
                'db_table_id' => 24,
                'return_to_menu_id' => 26,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            50 => 
            array (
                'id' => 30,
                'father_menu_id' => 28,
                'menu_title' => 'HOME_CARTAS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '510554cf118fc95de2b9d4f3c50d141c',
                'db_table_id' => 37,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            51 => 
            array (
                'id' => 3,
                'father_menu_id' => 2,
                'menu_title' => 'homes',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'fdc8e290421fe8e99a4833ca6851148e',
                'db_table_id' => 1,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            52 => 
            array (
                'id' => 63,
                'father_menu_id' => 31,
                'menu_title' => 'DB_MONTAR_ESTRUTURA',
                'route' => 'CRUD_VIEW',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '350c4983a110fb4ca8b22485ada8c51b',
                'db_table_id' => 9,
                'return_to_menu_id' => 60,
                'custom_crud_view' => 'Admin.Menus.view',
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            53 => 
            array (
                'id' => 29,
                'father_menu_id' => 28,
                'menu_title' => 'LISTAR_CARTAS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '6d44910fe843bb9b9b3ce4b54f27da74',
                'db_table_id' => 46,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            54 => 
            array (
                'id' => 64,
                'father_menu_id' => 5,
                'menu_title' => 'MENUS_LISTAR_MENU_ACTIONS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'f95c7754b516afc736b77d639647fdf3',
                'db_table_id' => 24,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            55 => 
            array (
                'id' => 42,
                'father_menu_id' => 5,
                'menu_title' => 'LISTAR_MENUS_RELACIONADOS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '72225452abd48f8a7326234a890269f3',
                'db_table_id' => 24,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            56 => 
            array (
                'id' => 65,
                'father_menu_id' => 5,
                'menu_title' => 'EDITAR_MENUS_RELACIONADOS',
                'route' => 'CRUD_VIEW',
                'opt_show_menu' => NULL,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '74a3c738207d3e025d296250ca5722e9',
                'db_table_id' => 24,
                'return_to_menu_id' => 42,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            57 => 
            array (
                'id' => 60,
                'father_menu_id' => 31,
                'menu_title' => 'DB_VIEW_DATABASE',
                'route' => 'CRUD_VIEW',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'e3d32941c8f66324f6f067f3718cfda8',
                'db_table_id' => 9,
                'return_to_menu_id' => 31,
                'custom_crud_view' => 'Admin.Menus.view',
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            58 => 
            array (
                'id' => 66,
                'father_menu_id' => 31,
                'menu_title' => 'DB_REFATORAR_TABELA',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 0,
                'class_fa_icon' => 'wrench',
                'menu_url_hash' => '3a5f8adc972ff33ba6acc4ad925f2ebf',
                'db_table_id' => 6,
                'return_to_menu_id' => 33,
                'custom_crud_view' => NULL,
                'custom_controller' => 'Tables',
                'custom_first_method_get' => 'refatorarEstrutura',
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            59 => 
            array (
                'id' => 500,
                'father_menu_id' => NULL,
                'menu_title' => 'SYSTEM',
                'route' => NULL,
                'opt_show_menu' => 1,
                'class_fa_icon' => 'icon-adm',
                'menu_url_hash' => 'bee68edb0831803be707445c59933d6d',
                'db_table_id' => NULL,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
            60 => 
            array (
                'id' => 67,
                'father_menu_id' => 44,
                'menu_title' => '_STATIC_LAYOUTS_DICTIONARY_TRANSLATE_',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '826aa10c3f33723a395741a784a526c0',
                'db_table_id' => 33,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ),
        ));
        
        echo "Setando o proximo valor para a sequencia incremental como: ";
        $tudo = \DB::table($tableName)
            ->orderBy('id', 'desc')
            ->limit(1)
            ->get(['id']);

        if ($tudo->isNotEmpty()) {
            $total_tabela = $tudo->first()->id;
        } else {
            $total_tabela = 0;
        }

        $total_tabela++;

        echo $total_tabela;

        \DB::statement("alter sequence admin.menus_id_seq restart with {$total_tabela}");

        echo PHP_EOL . PHP_EOL;
    }
}