<?php

namespace Database\Seeders;

use Database\Seeders\XisSeeder;

class AdminDbTableFieldTypesTableSeeder extends XisSeeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        $tableName = 'db_table_field_types';
        \DB::table($tableName)->delete();
        
        \DB::table($tableName)->insert(array (
            array (
                'id' => 1,
                'name' => 'bigint',
                'schema_table_type' => 'bigInteger',
                'schema_autoincrement' => 'bigIncrements',
                'schema_attributes' => NULL,
                'elasticsearch_type' => NULL,
                'is_searchable'     => false,
                'is_numeric'        => true,
                'is_string'         => false,
                'is_boolean'        => false,
                'is_datetime'       => false,
                'is_image'          => false,
                'is_password'       => false,
            ),
            array (
                'id' => 20,
                'name' => 'int',
                'schema_table_type' => 'integer',
                'schema_autoincrement' => 'increments',
                'schema_attributes' => NULL,
                'elasticsearch_type' => NULL,
                'is_searchable'     => false,
                'is_numeric'        => true,
                'is_string'         => false,
                'is_boolean'        => false,
                'is_datetime'       => false,
                'is_image'          => false,
                'is_password'       => false,
            ),
            array (
                'id' => 8,
                'name' => 'boolean',
                'schema_table_type' => 'boolean',
                'schema_autoincrement' => NULL,
                'schema_attributes' => NULL,
                'elasticsearch_type' => NULL,
                'is_searchable'     => false,
                'is_numeric'        => false,
                'is_string'         => false,
                'is_boolean'        => true,
                'is_datetime'       => false,
                'is_image'          => false,
                'is_password'       => false,
            ),
            array (
                'id' => 6,
                'name' => 'character',
                'schema_table_type' => 'char',
                'schema_autoincrement' => NULL,
                'schema_attributes' => NULL,
                'elasticsearch_type' => NULL,
                'is_searchable'     => true,
                'is_numeric'        => false,
                'is_string'         => true,
                'is_boolean'        => false,
                'is_datetime'       => false,
                'is_image'          => false,
                'is_password'       => false,
            ),
            array (
                'id' => 3,
                'name' => 'text',
                'schema_table_type' => 'text',
                'schema_autoincrement' => NULL,
                'schema_attributes' => NULL,
                'elasticsearch_type' => NULL,
                'is_searchable'     => true,
                'is_numeric'        => false,
                'is_string'         => true,
                'is_boolean'        => false,
                'is_datetime'       => false,
                'is_image'          => false,
                'is_password'       => false,
            ),
            array (
                'id' => 14,
                'name' => 'password',
                'schema_table_type' => 'string',
                'schema_autoincrement' => NULL,
                'schema_attributes' => NULL,
                'elasticsearch_type' => NULL,
                'is_searchable'     => false,
                'is_numeric'        => false,
                'is_string'         => true,
                'is_boolean'        => false,
                'is_datetime'       => false,
                'is_image'          => false,
                'is_password'       => true,
            ),
            array (
                'id' => 15,
                'name' => 'str_fa_icon',
                'schema_table_type' => 'string',
                'schema_autoincrement' => NULL,
                'schema_attributes' => NULL,
                'elasticsearch_type' => NULL,
                'is_searchable'     => true,
                'is_numeric'        => false,
                'is_string'         => true,
                'is_boolean'        => false,
                'is_datetime'       => false,
                'is_image'          => false,
                'is_password'       => false,
            ),
            array (
                'id' => 16,
                'name' => 'md5',
                'schema_table_type' => 'string',
                'schema_autoincrement' => NULL,
                'schema_attributes' => NULL,
                'elasticsearch_type' => NULL,
                'is_searchable'     => false,
                'is_numeric'        => false,
                'is_string'         => true,
                'is_boolean'        => false,
                'is_datetime'       => false,
                'is_image'          => false,
                'is_password'       => false,
            ),
            array (
                'id' => 12,
                'name' => 'date',
                'schema_table_type' => 'date',
                'schema_autoincrement' => NULL,
                'schema_attributes' => NULL,
                'elasticsearch_type' => NULL,
                'is_searchable'     => false,
                'is_numeric'        => false,
                'is_string'         => false,
                'is_boolean'        => false,
                'is_datetime'       => true,
                'is_image'          => false,
                'is_password'       => false,
            ),
            array (
                'id' => 19,
                'name' => 'datetime',
                'schema_table_type' => 'dateTime',
                'schema_autoincrement' => NULL,
                'schema_attributes' => NULL,
                'elasticsearch_type' => NULL,
                'is_searchable'     => false,
                'is_numeric'        => false,
                'is_string'         => false,
                'is_boolean'        => false,
                'is_datetime'       => true,
                'is_image'          => false,
                'is_password'       => false,
            ),
            array (
                'id' => 21,
                'name' => 'time',
                'schema_table_type' => 'time',
                'schema_autoincrement' => NULL,
                'schema_attributes' => NULL,
                'elasticsearch_type' => NULL,
                'is_searchable'     => false,
                'is_numeric'        => true,
                'is_string'         => false,
                'is_boolean'        => false,
                'is_datetime'       => true,
                'is_image'          => false,
                'is_password'       => false,
            ),
            array (
                'id' => 13,
                'name' => 'timestamp',
                'schema_table_type' => 'timestamp',
                'schema_autoincrement' => NULL,
                'schema_attributes' => NULL,
                'elasticsearch_type' => NULL,
                'is_searchable'     => false,
                'is_numeric'        => false,
                'is_string'         => false,
                'is_boolean'        => false,
                'is_datetime'       => true,
                'is_image'          => false,
                'is_password'       => false,
            ),
            array (
                'id' => 11,
                'name' => 'function',
                'schema_table_type' => 'text',
                'schema_autoincrement' => NULL,
                'schema_attributes' => NULL,
                'elasticsearch_type' => NULL,
                'is_searchable'     => false,
                'is_numeric'        => false,
                'is_string'         => true,
                'is_boolean'        => false,
                'is_datetime'       => false,
                'is_image'          => false,
                'is_password'       => false,
            ),
            array (
                'id' => 10,
                'name' => 'foreign',
                'schema_table_type' => 'bigInteger',
                'schema_autoincrement' => NULL,
                'schema_attributes' => NULL,
                'elasticsearch_type' => NULL,
                'is_searchable'     => false,
                'is_numeric'        => true,
                'is_string'         => false,
                'is_boolean'        => false,
                'is_datetime'       => false,
                'is_image'          => false,
                'is_password'       => false,
            ),
            array (
                'id' => 18,
                'name' => 'from_list',
                'schema_table_type' => 'enum',
                'schema_autoincrement' => NULL,
                'schema_attributes' => 'array:["default_value"]',
                'elasticsearch_type' => NULL,
                'is_searchable'     => false,
                'is_numeric'        => false,
                'is_string'         => true,
                'is_boolean'        => false,
                'is_datetime'       => false,
                'is_image'          => false,
                'is_password'       => false,
            ),
            array (
                'id' => 9,
                'name' => 'preset',
                'schema_table_type' => 'enum',
                'schema_autoincrement' => NULL,
                'schema_attributes' => 'array:["default_value"]',
                'elasticsearch_type' => NULL,
                'is_searchable'     => false,
                'is_numeric'        => false,
                'is_string'         => true,
                'is_boolean'        => false,
                'is_datetime'       => false,
                'is_image'          => false,
                'is_password'       => false,
            ),
            array (
                'id' => 2,
                'name' => 'string',
                'schema_table_type' => 'string',
                'schema_autoincrement' => NULL,
                'schema_attributes' => '1:["max_length"]',
                'elasticsearch_type' => NULL,
                'is_searchable'     => false,
                'is_numeric'        => false,
                'is_string'         => true,
                'is_boolean'        => false,
                'is_datetime'       => false,
                'is_image'          => false,
                'is_password'       => false,
            ),
            array (
                'id' => 4,
                'name' => 'float',
                'schema_table_type' => 'double',
                'schema_autoincrement' => NULL,
                'schema_attributes' => '2:["min_length","max_length"]',
                'elasticsearch_type' => NULL,
                'is_searchable'     => false,
                'is_numeric'        => true,
                'is_string'         => false,
                'is_boolean'        => false,
                'is_datetime'       => false,
                'is_image'          => false,
                'is_password'       => false,
            ),
            array (
                'id' => 5,
                'name' => 'currency',
                'schema_table_type' => 'decimal',
                'schema_autoincrement' => NULL,
                'schema_attributes' => '2:["min_length","max_length"]',
                'elasticsearch_type' => NULL,
                'is_searchable'     => false,
                'is_numeric'        => true,
                'is_string'         => false,
                'is_boolean'        => false,
                'is_datetime'       => false,
                'is_image'          => false,
                'is_password'       => false,
            ),
            array (
                'id' => 7,
                'name' => 'percentage',
                'schema_table_type' => 'double',
                'schema_autoincrement' => NULL,
                'schema_attributes' => '2:["min_length","max_length"]',
                'elasticsearch_type' => NULL,
                'is_searchable'     => false,
                'is_numeric'        => true,
                'is_string'         => false,
                'is_boolean'        => false,
                'is_datetime'       => false,
                'is_image'          => false,
                'is_password'       => false,
            ),
            array (
                'id' => 22,
                'name' => 'appendable',
                'schema_table_type' => 'string',
                'schema_autoincrement' => NULL,
                'schema_attributes' => null,
                'elasticsearch_type' => NULL,
                'is_searchable'     => false,
                'is_numeric'        => false,
                'is_string'         => false,
                'is_boolean'        => false,
                'is_datetime'       => false,
                'is_image'          => false,
                'is_password'       => false,
            ),
        ));
        
        echo "Setando o proximo valor para a sequencia incremental como: ";
        $tudo = \DB::table($tableName)
            ->orderBy('id', 'desc')
            ->limit(1)
            ->get(['id']);

        if ($tudo->isNotEmpty()) {
            $total_tabela = $tudo->first()->id;
        } else {
            $total_tabela = 0;
        }

        $total_tabela++;

        echo $total_tabela;

        \DB::statement("alter sequence admin.db_table_field_types_id_seq restart with {$total_tabela}");

        echo PHP_EOL . PHP_EOL;
    }
}