<?php

namespace Database\Seeders;

use Database\Seeders\XisSeeder;

class AdminMenusTableSeeder extends XisSeeder
{

    /**
     * Auto generated seed file
     *
     * self::getTableId('SEARCH_TABLE_NAME', 1), // 
     * 
     * @return void
     */
    public function run()
    {
        $tableName = 'menus';
        
        \DB::table($tableName)->delete();
        
        \DB::table($tableName)->insert([
            // [
            //     'id' => 1,
            //     'father_menu_id' => NULL,
            //     'menu_title' => 'HOME',
            //     'route' => 'HOME_URL',
            //     'opt_show_menu' => 1,
            //     'class_fa_icon' => 'icon-home',
            //     'menu_url_hash' => 'ebc11b9610e2dbc927c230572624a014',
            //     'table_id' => self::getTableId('home', 1), // 1,
            //     'return_to_menu_id' => NULL,
            //     'custom_crud_view' => NULL,
            //     'custom_controller' => NULL,
            //     'custom_first_method_get' => NULL,
            //     'system_id' => 1,
            //     'custom_first_method_post' => NULL,
            // ],
            [
                // 'id' => 100,
                'father_menu_id' => NULL,
                'menu_title' => 'ADMINISTRACAO',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'cogs',
                'menu_url_hash' => '9212b503339c08ed8a0360f0dd4912cd',
                'table_id' =>NULL,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            // [
            //     'id' => 200,
            //     'father_menu_id' => NULL,
            //     'menu_title' => 'CONTEUDO',
            //     'route' => 'DEFAULT_URL',
            //     'opt_show_menu' => 1,
            //     'class_fa_icon' => 'icon-prd',
            //     'menu_url_hash' => '8f11553e223f69cd6938f0e0a5ca3106',
            //     'table_id' =>NULL,
            //     'return_to_menu_id' => NULL,
            //     'custom_crud_view' => NULL,
            //     'custom_controller' => NULL,
            //     'custom_first_method_get' => NULL,
            //     'system_id' => 1,
            //     'custom_first_method_post' => NULL,
            // ],
            // [
            //     'id' => 300,
            //     'father_menu_id' => NULL,
            //     'menu_title' => 'MTG',
            //     'route' => 'DEFAULT_URL',
            //     'opt_show_menu' => 0,
            //     'class_fa_icon' => 'icon-mtg',
            //     'menu_url_hash' => 'a79441ea707855e0896395fd9baaf0db',
            //     'table_id' =>NULL,
            //     'return_to_menu_id' => NULL,
            //     'custom_crud_view' => NULL,
            //     'custom_controller' => NULL,
            //     'custom_first_method_get' => NULL,
            //     'system_id' => 1,
            //     'custom_first_method_post' => NULL,
            // ],
            // [
            //     'id' => 500,
            //     'father_menu_id' => NULL,
            //     'menu_title' => 'SYSTEM',
            //     'route' => NULL,
            //     'opt_show_menu' => 1,
            //     'class_fa_icon' => 'icon-adm',
            //     'menu_url_hash' => 'bee68edb0831803be707445c59933d6d',
            //     'table_id' =>NULL,
            //     'return_to_menu_id' => NULL,
            //     'custom_crud_view' => NULL,
            //     'custom_controller' => NULL,
            //     'custom_first_method_get' => NULL,
            //     'system_id' => 1,
            //     'custom_first_method_post' => NULL,
            // ],
        ]);
        
        \DB::table($tableName)->insert([
            [
                // 'id' => 4,
                'father_menu_id' => self::getMenuId('9212b503339c08ed8a0360f0dd4912cd'), // 100,
                'menu_title' => 'USUARIOS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'users',
                'menu_url_hash' => '987f94b6b2866343e9c54edd250fc259',
                'table_id' =>NULL,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],

            // [
            //     // 'id' => 43,
            //     'father_menu_id' => self::getMenuId('9212b503339c08ed8a0360f0dd4912cd'), // 100,
            //     'menu_title' => 'VISUALIZACAO',
            //     'route' => 'DEFAULT_URL',
            //     'opt_show_menu' => 1,
            //     'class_fa_icon' => 'screwdriver',
            //     'menu_url_hash' => 'd01fef50b51726275f3feca3c70e4dea',
            //     'table_id' => self::getTableId('menus', 1), // 3,
            //     'return_to_menu_id' => NULL,
            //     'custom_crud_view' => NULL,
            //     'custom_controller' => NULL,
            //     'custom_first_method_get' => NULL,
            //     'system_id' => 1,
            //     'custom_first_method_post' => NULL,
            // ],

            [
                // 'id' => 5,
                'father_menu_id' => self::getMenuId('9212b503339c08ed8a0360f0dd4912cd'), // 100,
                'menu_title' => 'MENUS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'bars',
                'menu_url_hash' => '9f6e4f167614a21b8de52e38531a1662',
                'table_id' =>NULL,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],

            // [
            //     // 'id' => 23,
            //     'father_menu_id' => self::getMenuId('9212b503339c08ed8a0360f0dd4912cd'), // 100,
            //     'menu_title' => 'IMPORTADOR',
            //     'route' => 'DEFAULT_URL',
            //     'opt_show_menu' => 1,
            //     'class_fa_icon' => 'arrow-down',
            //     'menu_url_hash' => '3625f554c8528bf453c5a695d6942f84',
            //     'table_id' =>NULL,
            //     'return_to_menu_id' => NULL,
            //     'custom_crud_view' => NULL,
            //     'custom_controller' => NULL,
            //     'custom_first_method_get' => NULL,
            //     'system_id' => 1,
            //     'custom_first_method_post' => NULL,
            // ],

            [
                // 'id' => 31,
                'father_menu_id' => self::getMenuId('9212b503339c08ed8a0360f0dd4912cd'), // 100,
                'menu_title' => 'DATABASE',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'database',
                'menu_url_hash' => '965ac7557dc20d67047043ecbed46ae4',
                'table_id' =>NULL,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],

            [
                // 'id' => 44,
                'father_menu_id' => self::getMenuId('9212b503339c08ed8a0360f0dd4912cd'), // 100,
                'menu_title' => 'DICTIONARY',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'book',
                'menu_url_hash' => 'dca0aae7fb14c689e8757742c76045a6',
                'table_id' => self::getTableId('users', 1), // 2,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],

            [
                // 'id' => 400,
                'father_menu_id' => self::getMenuId('9212b503339c08ed8a0360f0dd4912cd'), // 100,
                'menu_title' => 'PERFIS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'address-card',
                'menu_url_hash' => 'fdbcc17be502e5192b8dfe1edfdfba38',
                'table_id' => self::getTableId('users', 1), // 2,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],

            [
                // 'id' => 400,
                'father_menu_id' => self::getMenuId('9212b503339c08ed8a0360f0dd4912cd'), // 100,
                'menu_title' => 'TESTES',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'config',
                'menu_url_hash' => '8084d2014eff3a7b21d7d031f36279eb',
                'table_id' => self::getTableId('tests_table', 1), // 2,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            
        ]);
        
        \DB::table($tableName)->insert([
            // [
            //     'id' => 2,
            //     'father_menu_id' => 1,
            //     'menu_title' => 'Home',
            //     'route' => 'HOME_URL',
            //     'opt_show_menu' => 1,
            //     'class_fa_icon' => NULL,
            //     'menu_url_hash' => '8084d2014eff3a7b21d7d031f36279eb',
            //     'table_id' => self::getTableId('home', 1), // 1,
            //     'return_to_menu_id' => NULL,
            //     'custom_crud_view' => NULL,
            //     'custom_controller' => NULL,
            //     'custom_first_method_get' => NULL,
            //     'system_id' => 1,
            //     'custom_first_method_post' => NULL,
            // ],
            [
                'father_menu_id' => self::getMenuId('fdbcc17be502e5192b8dfe1edfdfba38'), // 400
                'menu_title' => 'EDITAR_PERFIL',
                'route' => 'CRUD_VIEW',
                'opt_show_menu' => false,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'dc211d992b7e397b158d3103f2b9cf5a',
                'table_id' => self::getTableId('roles', 1), // 21,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('fdbcc17be502e5192b8dfe1edfdfba38'), // 400
                'menu_title' => 'LISTAR_PERFIS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'de2e2b248a0ba65ed3f11c2bdf6c9a53',
                'table_id' => self::getTableId('roles', 1), // 21,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('965ac7557dc20d67047043ecbed46ae4'), // 31
                'menu_title' => 'LISTAR_TABELAS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'table',
                'menu_url_hash' => '71deca3bdc0f642e4ce1fa892929da7a',
                'table_id' => self::getTableId('db_tables', 1), // 6,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('965ac7557dc20d67047043ecbed46ae4'), // 31
                'menu_title' => 'LISTAR_CAMPOS_TABELA',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'b832bac46147eab1b8dde6852058f864',
                'table_id' => self::getTableId('db_table_fields', 1), // 11,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('fdbcc17be502e5192b8dfe1edfdfba38'), // 400
                'menu_title' => 'VIEW_ROLE',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '972dc026d07b74a3918783b74a929cd6',
                'table_id' =>NULL,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('987f94b6b2866343e9c54edd250fc259'), // 4
                'menu_title' => 'ADICIONAR_USUARIO',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'c038d4c071567f8673f2e51a4069f25c',
                'table_id' => self::getTableId('users', 1), // 2,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('987f94b6b2866343e9c54edd250fc259'), // 4
                'menu_title' => 'EDITAR_USUARIO',
                'route' => 'CRUD_VIEW',
                'opt_show_menu' => NULL,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '7475ae2fd02e1086cea4973630445a45',
                'table_id' => self::getTableId('users', 1), // 2,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('dca0aae7fb14c689e8757742c76045a6'), // 44
                'menu_title' => 'EDIT_DICTIONARY_WORD',
                'route' => 'CRUD_VIEW',
                'opt_show_menu' => NULL,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'ea134e4b4256fc2f0f88109021c9b07f',
                'table_id' => self::getTableId('dictionary', 1), // 32,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('dca0aae7fb14c689e8757742c76045a6'), // 44
                'menu_title' => 'ADD_DICTIONARY_TRANSLATION',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '9ae9cb587594021cd28e7cce953d97f6',
                'table_id' => self::getTableId('dictionary_translations', 1), // 33,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('965ac7557dc20d67047043ecbed46ae4'), // 31
                'menu_title' => 'RELACIONAR_CAMPOS_TABELA',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '79784338ee2e9c6c1185a24465f743db',
                'table_id' => self::getTableId('db_table_field_joins', 1), // 13,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('965ac7557dc20d67047043ecbed46ae4'), // 31
                'menu_title' => 'LIST_FIELD_JOINTS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '072d411b7681fc2091418482db2735ad',
                'table_id' => self::getTableId('db_table_field_joins', 1), // 13,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            // [
            //     'id' => 11,
            //     'father_menu_id' => 200,
            //     'menu_title' => 'MODELOS',
            //     'route' => 'DEFAULT_URL',
            //     'opt_show_menu' => 1,
            //     'class_fa_icon' => NULL,
            //     'menu_url_hash' => '079d8e7f8990b3a5d281798269d0b79d',
            //     'table_id' =>NULL,
            //     'return_to_menu_id' => NULL,
            //     'custom_crud_view' => NULL,
            //     'custom_controller' => NULL,
            //     'custom_first_method_get' => NULL,
            //     'system_id' => 1,
            //     'custom_first_method_post' => NULL,
            // ],
            // [
            //     'id' => 10,
            //     'father_menu_id' => 200,
            //     'menu_title' => 'PRODUTOS',
            //     'route' => 'DEFAULT_URL',
            //     'opt_show_menu' => 1,
            //     'class_fa_icon' => 'icon-prd',
            //     'menu_url_hash' => '90b370c685f47bc1f300559a24d4b03c',
            //     'table_id' =>NULL,
            //     'return_to_menu_id' => NULL,
            //     'custom_crud_view' => NULL,
            //     'custom_controller' => NULL,
            //     'custom_first_method_get' => NULL,
            //     'system_id' => 1,
            //     'custom_first_method_post' => NULL,
            // ],
            // [
            //     'id' => 28,
            //     'father_menu_id' => 300,
            //     'menu_title' => 'CARTAS',
            //     'route' => 'DEFAULT_URL',
            //     'opt_show_menu' => 1,
            //     'class_fa_icon' => NULL,
            //     'menu_url_hash' => '4c1ce9bd11d5e36158c4d8fa3dc8e9f1',
            //     'table_id' =>NULL,
            //     'return_to_menu_id' => NULL,
            //     'custom_crud_view' => NULL,
            //     'custom_controller' => NULL,
            //     'custom_first_method_get' => NULL,
            //     'system_id' => 1,
            //     'custom_first_method_post' => NULL,
            // ],
            [
                'father_menu_id' => self::getMenuId('9f6e4f167614a21b8de52e38531a1662'), // 5
                'menu_title' => 'ADICIONAR_MENU',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => false,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'f7297421861662291eddeb6179378a0d',
                'table_id' => self::getTableId('menus', 1), // 3,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('965ac7557dc20d67047043ecbed46ae4'), // 31
                'menu_title' => 'ADICIONAR_TABELA',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => false,
                'class_fa_icon' => 'table',
                'menu_url_hash' => '51d1147595b4dc439c0cb4683ccd7322',
                'table_id' => self::getTableId('db_tables', 1), // 6,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            // [
            //     'id' => 8,
            //     'father_menu_id' => 200,
            //     'menu_title' => 'ARTIGOS',
            //     'route' => 'DEFAULT_URL',
            //     'opt_show_menu' => 1,
            //     'class_fa_icon' => NULL,
            //     'menu_url_hash' => '784949445fe212956e95a460fb824d7c',
            //     'table_id' =>NULL,
            //     'return_to_menu_id' => NULL,
            //     'custom_crud_view' => NULL,
            //     'custom_controller' => NULL,
            //     'custom_first_method_get' => NULL,
            //     'system_id' => 1,
            //     'custom_first_method_post' => NULL,
            // ],
            [
                'father_menu_id' => self::getMenuId('987f94b6b2866343e9c54edd250fc259'), // 4
                'menu_title' => 'LISTAR_USUARIOS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'bf4fc0f7f9966228b29a2b6e1813f0b7',
                'table_id' => self::getTableId('users', 1), // 2,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('965ac7557dc20d67047043ecbed46ae4'), // 31
                'menu_title' => 'EDITAR_TABELA',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '997423f712aa8fd8e10f38a9afbb3c48',
                'table_id' => self::getTableId('db_tables', 1), // 6,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('dca0aae7fb14c689e8757742c76045a6'), // 44
                'menu_title' => 'LIST_DICTIONARY_WORDS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '08bc460efd6d7b6b5501bf115c8c7ebe',
                'table_id' => self::getTableId('dictionary', 1), // 32,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('9f6e4f167614a21b8de52e38531a1662'), // 5
                'menu_title' => 'EDITAR_MENU',
                'route' => 'CRUD_VIEW',
                'opt_show_menu' => NULL,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'c6177de3c5d54b9edc1e2e04fcfe43d5',
                'table_id' => self::getTableId('menus', 1), // 3,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            // [
            //     'id' => 9,
            //     'father_menu_id' => 8,
            //     'menu_title' => 'LISTAR_ARTIGOS',
            //     'route' => 'DEFAULT_URL',
            //     'opt_show_menu' => 1,
            //     'class_fa_icon' => 'icon-prd',
            //     'menu_url_hash' => '1cf31abde0e4254b12fc09c499933f64',
            //     'table_id' => self::getTableId('articles', 2), // 37,
            //     'return_to_menu_id' => NULL,
            //     'custom_crud_view' => NULL,
            //     'custom_controller' => NULL,
            //     'custom_first_method_get' => NULL,
            //     'system_id' => 1,
            //     'custom_first_method_post' => NULL,
            // ],
            [
                'father_menu_id' => self::getMenuId('965ac7557dc20d67047043ecbed46ae4'), // 31
                'menu_title' => 'EDITAR_CAMPO_EXTRANGEIRO',
                'route' => 'CRUD_VIEW',
                'opt_show_menu' => NULL,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '8f05329a3c2a90e9f2b6fa3f5e822273',
                'table_id' => self::getTableId('db_table_field_joins', 1), // 13,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('965ac7557dc20d67047043ecbed46ae4'), // 31
                'menu_title' => 'ADICIONAR_CAMPOS_TABELA',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '48d507a1af1f3f26b0d96ab176107a96',
                'table_id' => self::getTableId('db_table_fields', 1), // 11,
                'return_to_menu_id' => 37,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('965ac7557dc20d67047043ecbed46ae4'), // 31
                'menu_title' => 'EDITAR_CAMPO_TABELA',
                'route' => 'CRUD_VIEW',
                'opt_show_menu' => NULL,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '0d305d3368202beb084b757d11394e31',
                'table_id' => self::getTableId('db_table_fields', 1), // 11,
                'return_to_menu_id' => 37,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            // [
            //     'id' => 22,
            //     'father_menu_id' => 8,
            //     'menu_title' => 'VIEW_ARTIGO',
            //     'route' => 'DEFAULT_URL',
            //     'opt_show_menu' => 0,
            //     'class_fa_icon' => NULL,
            //     'menu_url_hash' => 'cf4f1627d6deceec9e44960a34e8c3a1',
            //     'table_id' =>NULL,
            //     'return_to_menu_id' => 22,
            //     'custom_crud_view' => NULL,
            //     'custom_controller' => NULL,
            //     'custom_first_method_get' => NULL,
            //     'system_id' => 1,
            //     'custom_first_method_post' => NULL,
            // ],
            [
                'father_menu_id' => self::getMenuId('965ac7557dc20d67047043ecbed46ae4'), // 31
                'menu_title' => 'LIST_DATABASES',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'database',
                'menu_url_hash' => '2fdce19f21d3424597bbfc92a269bce3',
                'table_id' => self::getTableId('databases', 1), // 9,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            // [
            //     'id' => 25,
            //     'father_menu_id' => 23,
            //     'menu_title' => 'INSERIR_IMPORTADOR',
            //     'route' => 'DEFAULT_URL',
            //     'opt_show_menu' => 0,
            //     'class_fa_icon' => NULL,
            //     'menu_url_hash' => 'd168545cfcb74d58de1b443e604f6954',
            //     'table_id' => self::getTableId('importers', 1), // 15,
            //     'return_to_menu_id' => NULL,
            //     'custom_crud_view' => NULL,
            //     'custom_controller' => NULL,
            //     'custom_first_method_get' => NULL,
            //     'system_id' => 1,
            //     'custom_first_method_post' => NULL,
            // ],
            // [
            //     'id' => 12,
            //     'father_menu_id' => 10,
            //     'menu_title' => 'LISTAR_PRODUTOS',
            //     'route' => 'DEFAULT_URL',
            //     'opt_show_menu' => 1,
            //     'class_fa_icon' => NULL,
            //     'menu_url_hash' => '087191174a91f7d5a73acb8a1d760a34',
            //     'table_id' => self::getTableId('produtos', 2), // 39,
            //     'return_to_menu_id' => NULL,
            //     'custom_crud_view' => NULL,
            //     'custom_controller' => NULL,
            //     'custom_first_method_get' => NULL,
            //     'system_id' => 1,
            //     'custom_first_method_post' => NULL,
            // ],
            [
                'father_menu_id' => self::getMenuId('9f6e4f167614a21b8de52e38531a1662'), // 5
                'menu_title' => 'LISTAR_MENUS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '24c007b328f19943bc53bf4715f9fe6b',
                'table_id' => self::getTableId('menus', 1), // 3,
                'return_to_menu_id' => 48,
                'custom_crud_view' => NULL,
                'custom_controller' => 'Menus',
                'custom_first_method_get' => 'index',
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            // [
            //     'id' => 24,
            //     'father_menu_id' => 23,
            //     'menu_title' => 'IMPORTADOR',
            //     'route' => 'DEFAULT_URL',
            //     'opt_show_menu' => 1,
            //     'class_fa_icon' => NULL,
            //     'menu_url_hash' => 'cee5d729e0f43173fc56d65ec4afb222',
            //     'table_id' => self::getTableId('importers', 1), // 15,
            //     'return_to_menu_id' => NULL,
            //     'custom_crud_view' => NULL,
            //     'custom_controller' => NULL,
            //     'custom_first_method_get' => NULL,
            //     'system_id' => 1,
            //     'custom_first_method_post' => NULL,
            // ],
            [
                'father_menu_id' => self::getMenuId('965ac7557dc20d67047043ecbed46ae4'), // 31
                'menu_title' => 'RELACIONAR_TABELAS',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => 1,
                'class_fa_icon' => 'database',
                'menu_url_hash' => '5d6be589684984505435e6b53a6874f7',
                'table_id' => self::getTableId('db_related_tables', 1), // 23,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('9f6e4f167614a21b8de52e38531a1662'), // 5
                'menu_title' => 'MENU_LIST_ACTIONS_ADD',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '673acf5da3f4a2a96293ff0fb3781eea',
                'table_id' => self::getTableId('menu_list_actions', 1), // 31,
                'return_to_menu_id' => 26,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('965ac7557dc20d67047043ecbed46ae4'), // 31
                'menu_title' => 'ADMIN_DB_ADD_DATABASE',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '99e8f8df060c56aec39585267bd99f5e',
                'table_id' => self::getTableId('databases', 1), // 9,
                'return_to_menu_id' => 59,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            // [
            //     'id' => 13,
            //     'father_menu_id' => 11,
            //     'menu_title' => 'LISTAR_MODELOS',
            //     'route' => 'DEFAULT_URL',
            //     'opt_show_menu' => 1,
            //     'class_fa_icon' => NULL,
            //     'menu_url_hash' => '41fa02c4e9a3ecbcde545b8bd7e3c9ec',
            //     'table_id' => self::getTableId('modelos', 2), // 38,
            //     'return_to_menu_id' => NULL,
            //     'custom_crud_view' => NULL,
            //     'custom_controller' => NULL,
            //     'custom_first_method_get' => NULL,
            //     'system_id' => 1,
            //     'custom_first_method_post' => NULL,
            // ],
            [
                'father_menu_id' => self::getMenuId('9f6e4f167614a21b8de52e38531a1662'), // 5
                'menu_title' => 'ADMIN_MENUS_ADD_RELATED_MENU',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '132878f048adc0cb452f43bca3abcd60',
                'table_id' => self::getTableId('menus_related', 1), // 24,
                'return_to_menu_id' => 26,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            // [
            //     'id' => 30,
            //     'father_menu_id' => 28,
            //     'menu_title' => 'HOME_CARTAS',
            //     'route' => 'DEFAULT_URL',
            //     'opt_show_menu' => 0,
            //     'class_fa_icon' => NULL,
            //     'menu_url_hash' => '510554cf118fc95de2b9d4f3c50d141c',
            //     'table_id' => self::getTableId('articles', 2), // 37,
            //     'return_to_menu_id' => NULL,
            //     'custom_crud_view' => NULL,
            //     'custom_controller' => NULL,
            //     'custom_first_method_get' => NULL,
            //     'system_id' => 1,
            //     'custom_first_method_post' => NULL,
            // ],
            // [
            //     'id' => 3,
            //     'father_menu_id' => 2,
            //     'menu_title' => 'homes',
            //     'route' => 'DEFAULT_URL',
            //     'opt_show_menu' => 1,
            //     'class_fa_icon' => NULL,
            //     'menu_url_hash' => 'fdc8e290421fe8e99a4833ca6851148e',
            //     'table_id' => self::getTableId('home', 1), // 1,
            //     'return_to_menu_id' => NULL,
            //     'custom_crud_view' => NULL,
            //     'custom_controller' => NULL,
            //     'custom_first_method_get' => NULL,
            //     'system_id' => 1,
            //     'custom_first_method_post' => NULL,
            // ],
            [
                'father_menu_id' => self::getMenuId('965ac7557dc20d67047043ecbed46ae4'), // 31
                'menu_title' => 'DB_MONTAR_ESTRUTURA',
                'route' => 'CRUD_VIEW',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '350c4983a110fb4ca8b22485ada8c51b',
                'table_id' => self::getTableId('databases', 1), // 9,
                'return_to_menu_id' => 60,
                'custom_crud_view' => 'Admin.Menus.view',
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            // array (
            //     'id' => 29,
            //     'father_menu_id' => 28,
            //     'menu_title' => 'LISTAR_CARTAS',
            //     'route' => 'DEFAULT_URL',
            //     'opt_show_menu' => 1,
            //     'class_fa_icon' => NULL,
            //     'menu_url_hash' => '6d44910fe843bb9b9b3ce4b54f27da74',
            //     'table_id' => self::getTableId('cards', 3), // 46,
            //     'return_to_menu_id' => NULL,
            //     'custom_crud_view' => NULL,
            //     'custom_controller' => NULL,
            //     'custom_first_method_get' => NULL,
            //     'system_id' => 1,
            //     'custom_first_method_post' => NULL,
            // ),
            [
                'father_menu_id' => self::getMenuId('9f6e4f167614a21b8de52e38531a1662'), // 5
                'menu_title' => 'MENUS_LISTAR_MENU_ACTIONS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'f95c7754b516afc736b77d639647fdf3',
                'table_id' => self::getTableId('menus_related', 1), // 24,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('9f6e4f167614a21b8de52e38531a1662'), // 5
                'menu_title' => 'LISTAR_MENUS_RELACIONADOS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '72225452abd48f8a7326234a890269f3',
                'table_id' => self::getTableId('menus_related', 1), // 24,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('9f6e4f167614a21b8de52e38531a1662'), // 5
                'menu_title' => 'EDITAR_MENUS_RELACIONADOS',
                'route' => 'CRUD_VIEW',
                'opt_show_menu' => NULL,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '74a3c738207d3e025d296250ca5722e9',
                'table_id' => self::getTableId('menus_related', 1), // 24,
                'return_to_menu_id' => 42,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('965ac7557dc20d67047043ecbed46ae4'), // 31
                'menu_title' => 'DB_VIEW_DATABASE',
                'route' => 'CRUD_VIEW',
                'opt_show_menu' => 0,
                'class_fa_icon' => NULL,
                'menu_url_hash' => 'e3d32941c8f66324f6f067f3718cfda8',
                'table_id' => self::getTableId('databases', 1), // 9,
                'return_to_menu_id' => 31,
                'custom_crud_view' => 'Admin.Menus.view',
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('965ac7557dc20d67047043ecbed46ae4'), // 31
                'menu_title' => 'DB_REFATORAR_TABELA',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 0,
                'class_fa_icon' => 'wrench',
                'menu_url_hash' => '3a5f8adc972ff33ba6acc4ad925f2ebf',
                'table_id' => self::getTableId('db_tables', 1), // 6,
                'return_to_menu_id' => 33,
                'custom_crud_view' => NULL,
                'custom_controller' => 'Tables',
                'custom_first_method_get' => 'refatorarEstrutura',
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('dca0aae7fb14c689e8757742c76045a6'), // 44
                'menu_title' => '_STATIC_LAYOUTS_DICTIONARY_TRANSLATE_',
                'route' => 'CRUD_INSERT',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '826aa10c3f33723a395741a784a526c0',
                'table_id' => self::getTableId('dictionary_translations', 1), // 33,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
            [
                'father_menu_id' => self::getMenuId('8084d2014eff3a7b21d7d031f36279eb'), // 44
                'menu_title' => 'LIST_TESTS',
                'route' => 'DEFAULT_URL',
                'opt_show_menu' => 1,
                'class_fa_icon' => NULL,
                'menu_url_hash' => '6d44910fe843bb9b9b3ce4b54f27da74',
                'table_id' => self::getTableId('tests_table', 1), // 33,
                'return_to_menu_id' => NULL,
                'custom_crud_view' => NULL,
                'custom_controller' => NULL,
                'custom_first_method_get' => NULL,
                'system_id' => 1,
                'custom_first_method_post' => NULL,
            ],
        ]);
        
        echo "Setando o proximo valor para a sequencia incremental como: ";
        $tudo = \DB::table($tableName)
            ->orderBy('id', 'desc')
            ->limit(1)
            ->get(['id']);

        if ($tudo->isNotEmpty()) {
            $total_tabela = $tudo->first()->id;
        } else {
            $total_tabela = 0;
        }

        $total_tabela++;

        echo $total_tabela;

        \DB::statement("alter sequence admin.menus_id_seq restart with {$total_tabela}");

        echo PHP_EOL . PHP_EOL;
    }
}